name: Maintain Streak

on:
  schedule:
    # Runs every day at midnight UTC (5:30 am IST)
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set commit author
      - name: Set commit author
        run: |
          git config --global user.name "Rakesh9100"
          git config --global user.email "roshanrakesh7362@gmail.com"

      # Step 3: Update the streak stats URL
      - name: Update the streak stats URL
        run: |
          today=$(date "+%d-%m-%Y")
          sed -i -E "s/(date=)[0-9-]+/\1$today/" README.md

      # Step 4: Commit and push the changes
      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Update README with the latest progress"
          git push
        # Make this step continue even if the commit doesn't change anything
        continue-on-error: true
